# Generated by Django 6.1 on 2026-08-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persos_preferidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_externo', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('image', models.URLField()),
            ],
        ),
    ]
