# Generated by Django 6.1 on 2026-08-29 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpisodioFavorito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_externo', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('air_date', models.CharField(max_length=100)),
                ('episode', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LocalizacaoFavorita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_externo', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=100)),
                ('dimension', models.CharField(max_length=255)),
            ],
        ),
    ]
