# Generated by Django 6.1 on 2026-08-29 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_episodiofavorito_localizacaofavorita'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonagemFav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_externo', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=254)),
                ('status', models.CharField(max_length=100)),
                ('species', models.CharField(max_length=100)),
                ('type', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(max_length=50)),
                ('image', models.URLField()),
            ],
        ),
        migrations.RenameModel(
            old_name='EpisodioFavorito',
            new_name='EpisodioFav',
        ),
        migrations.RenameModel(
            old_name='LocalizacaoFavorita',
            new_name='LocalizacaoFav',
        ),
        migrations.DeleteModel(
            name='Persos_preferidos',
        ),
    ]
