# Generated by Django 6.1 on 2026-08-30 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_personagemfav_rename_episodiofavorito_episodiofav_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episodiofav',
            name='pasta',
            field=models.CharField(blank=True, default='Geral', max_length=100),
        ),
        migrations.AddField(
            model_name='localizacaofav',
            name='pasta',
            field=models.CharField(blank=True, default='Geral', max_length=100),
        ),
        migrations.AddField(
            model_name='personagemfav',
            name='pasta',
            field=models.CharField(blank=True, default='Geral', max_length=100),
        ),
    ]
