# Generated by Django 6.1 on 2026-08-30 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_episodiofav_pasta_localizacaofav_pasta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastaFavoritos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='episodiofav',
            name='pasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='episodios', to='app.pastafavoritos'),
        ),
        migrations.AlterField(
            model_name='localizacaofav',
            name='pasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localizacoes', to='app.pastafavoritos'),
        ),
        migrations.AlterField(
            model_name='personagemfav',
            name='pasta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personagens', to='app.pastafavoritos'),
        ),
    ]
